name: GitLab Upgrade

on:
  push:
    branches:
      - master  

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Ansible version 
        run: echo "ANSIBLE_FORCE_LEGACY_PYTHON=1" >> <span class="math-inline">GITHUB\_ENV
\- name\: Install Ansible
run\: \|
sudo apt\-get update
sudo apt\-get install \-y ansible
\- name\: Configure SSH connection
run\: \|
mkdir \-p \~/\.ssh
echo "</span>{{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          ssh-keyscan <span class="math-inline">\{\{ secrets\.GITLAB\_HOST \}\} \>\> \~/\.ssh/known\_hosts
\- name\: Check Ansible and Python versions
run\: \|
ansible \-\-version
ssh azureuser@</span>{{ secrets.GITLAB_HOST }} '
