name: GitLab Upgrade

on:
  push:
    branches:
      - master 

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Configure SSH connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.GITLAB_HOST }} >> ~/.ssh/known_hosts

      - name: Run Ansible playbook (17.0)
        run: ansible-playbook -i inventory gitlab_upgrade.yml

      - name: Update playbook for 17.3
        run: |
          sed -i 's/target_version: 17.0/target_version: 17.3/g' gitlab_upgrade.yml
          # Add your updated version_check.sh logic here for 17.0 to 17.3
          cat << EOF > version_check.sh
          #!/bin/bash

          # ... (rest of the script) ...

          check_upgrade_path() {
            local current="$1"
            local target="$2"

            case "$current" in
              "17.0")
                # Valid upgrade paths from 17.0
                if [[ "$target" == "17.1" || "$target" == "17.2" || "$target" == "17.3" ]]; then
                  return 0
                fi
                ;;
              *)
                echo "Upgrade path not defined for $current"
                return 1
                ;;
            esac

            return 1  # If no match was found, the upgrade is not valid
          }

          # ... (rest of the script) ...
          EOF
          chmod +x version_check.sh

      - name: Run Ansible playbook (17.3)
        run: ansible-playbook -i inventory gitlab_upgrade.yml
