name: GitLab Upgrade

on:
  push:
    branches:
      - master

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Configure SSH connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.GITLAB_HOST }} >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.txt
          chmod 600 private_key.txt
          ssh-add private_key.txt

      - name: Check Ansible and Python versions
        run: |
          ansible --version
          ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.GITLAB_HOST }} 'python3 --version'

      - name: Upgrade to 17.0
        run: |
          ansible-playbook -i inventory gitlab_upgrade.yml -e "ansible_python_interpreter=/usr/bin/python3.6"

      - name: Upgrade to 17.3
        run: |
          sed -i 's/target_version: 17.0/target_version: 17.3/g' gitlab_upgrade.yml
          ansible-playbook -i inventory gitlab_upgrade.yml -e "ansible_python_interpreter=/usr/bin/python3.6"
