name: GitLab Upgrade

on:
  push:
    branches:
      - master

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible 2.9
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install ansible==2.9.27  # Install Ansible 2.9.27

      - name: Configure SSH connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          ssh-keyscan <span class="math-inline">\{\{ secrets\.GITLAB\_HOST \}\} \>\> \~/\.ssh/known\_hosts
eval "</span>(ssh-agent -s)"
          echo "<span class="math-inline">\{\{ secrets\.SSH\_PRIVATE\_KEY \}\}" \> private\_key\.txt
chmod 600 private\_key\.txt
ssh\-add private\_key\.txt
\- name\: Check Ansible and Python versions
run\: \|
ansible \-\-version
ssh \-o StrictHostKeyChecking\=no azureuser@</span>{{ secrets.GITLAB_HOST }} 'python3 --version'

      - name: Upgrade to 17.0 and then 17.3
        run: |
          ansible-playbook -i inventory gitlab_upgrade.yml -e "ansible_python_interpreter=/usr/bin/python3"
          if [[ $? -eq 0 ]]; then
            echo "Upgrade to 17.0 successful. Proceeding to 17.3"
            sed
