name: GitLab Upgrade Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  ANSIBLE_HOST_KEY_CHECKING: False

jobs:
  upgrade_gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.GITLAB_HOST }}" >> ~/.ssh/known_hosts

      - name: Copy version_check.sh to GitLab server
        run: |
          echo "${{ secrets.VERSION_CHECK_SCRIPT }}" > version_check.sh
          chmod +x version_check.sh
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no version_check.sh azureuser@${{ secrets.GITLAB_HOST }}:/tmp/version_check.sh
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no azureuser@${{ secrets.GITLAB_HOST }} "chmod +x /tmp/version_check.sh"

      - name: Validate Upgrade Path
        run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no azureuser@${{ secrets.GITLAB_HOST }} "sudo bash /tmp/version_check.sh ${{ secrets.TARGET_VERSION }}"

      - name: Upgrade Python on Server
        run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no azureuser@${{ secrets.GITLAB_HOST }} "
          sudo yum install -y python38 python38-pip &&
          sudo alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1 &&
          sudo alternatives --set python3 /usr/bin/python3.8 &&
          python3 --version"

      - name: Run Ansible Playbook to Upgrade GitLab
        run: ansible-playbook -i inventory gitlab_upgrade.yml -e "ansible_python_interpreter=/usr/bin/python3 target_version=${{ secrets.TARGET_VERSION }}"

      - name: Verify GitLab Version
        run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no azureuser@${{ secrets.GITLAB_HOST }} "sudo /opt/gitlab/bin/gitlab-rake gitlab:env:info | grep 'Version:'"
