name: GitLab Upgrade

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Configure SSH connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GITLAB_HOST }} >> ~/.ssh/known_hosts

      - name: Validate Upgrade Path
        run: |
          chmod +x version_check.sh
          ./version_check.sh
        env:
          GITLAB_HOST: ${{ secrets.GITLAB_HOST }}

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory gitlab_upgrade.yml -e "ansible_python_interpreter=/usr/bin/python3 target_version=17.0"
          ansible-playbook -i inventory gitlab_upgrade.yml -e "ansible_python_interpreter=/usr/bin/python3 target_version=17.3"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"

      - name: Verify Upgrade
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.GITLAB_HOST }} '/opt/gitlab/bin/gitlab-rake gitlab:env:info | grep "GitLab version"'
