name: GitLab Upgrade

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify and Upgrade Python on GitLab Server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no azureuser@${{ secrets.GITLAB_HOST }} "
            sudo yum install -y gcc libffi-devel bzip2 bzip2-devel zlib-devel openssl-devel xz-devel &&
            wget https://www.python.org/ftp/python/3.9.9/Python-3.9.9.tgz &&
            tar xvf Python-3.9.9.tgz &&
            cd Python-3.9.9 &&
            ./configure --enable-optimizations &&
            sudo make altinstall &&
            sudo alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.9 1
          "

      - name: Validate Upgrade Path
        id: validate-upgrade
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no azureuser@${{ secrets.GITLAB_HOST }} "sudo /tmp/version_check.sh"
        continue-on-error: true

      - name: Upgrade to 17.0
        if: steps.validate-upgrade.outcome == 'failure'
        run: |
          echo "Performing intermediate upgrade to 17.0"
          ansible-playbook -i inventory gitlab_upgrade.yml -e "ansible_python_interpreter=/usr/bin/python3.9 target_version=17.0"

      - name: Re-Validate Upgrade Path
        if: steps.validate-upgrade.outcome == 'failure'
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no azureuser@${{ secrets.GITLAB_HOST }} "sudo /tmp/version_check.sh"

      - name: Upgrade to 17.3
        if: steps.re-validate-upgrade.outcome == 'success'
        run: |
          echo "Performing upgrade to 17.3"
          ansible-playbook -i inventory gitlab_upgrade.yml -e "ansible_python_interpreter=/usr/bin/python3.9 target_version=17.3"

      - name: Verify Final Version
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no azureuser@${{ secrets.GITLAB_HOST }} "sudo /opt/gitlab/bin/gitlab-rake gitlab:env:info | grep 'Version:'"
