name: GitLab Upgrade Pipeline

on:
  push:
    branches:
      - master

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        touch ~/.ssh/known_hosts
        ssh-keyscan -H ${{ secrets.GITLAB_HOST }} >> ~/.ssh/known_hosts

    - name: Copy Version Check Script to Server
      run: |
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no version_check.sh azureuser@${{ secrets.GITLAB_HOST }}:/tmp/version_check.sh
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no azureuser@${{ secrets.GITLAB_HOST }} "sudo chmod +x /tmp/version_check.sh"

    - name: Validate Upgrade Path
      id: validate-path
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no azureuser@${{ secrets.GITLAB_HOST }} "sudo /tmp/version_check.sh 17.0"
      continue-on-error: true

    - name: Upgrade GitLab to Intermediate Version
      if: steps.validate-path.outcome == 'failure'
      run: |
        ansible-playbook -i inventory gitlab_upgrade.yml -e "ansible_python_interpreter=/usr/bin/python3.8 target_version=17.0"

    - name: Re-Validate Upgrade Path
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no azureuser@${{ secrets.GITLAB_HOST }} "sudo /tmp/version_check.sh 17.3"

    - name: Upgrade GitLab to Final Version
      run: |
        ansible-playbook -i inventory gitlab_upgrade.yml -e "ansible_python_interpreter=/usr/bin/python3.8 target_version=17.3"
