name: GitLab Upgrade

on:
  push:
    branches:
      - master  

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Configure SSH connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -F "${{ secrets.GITLAB_HOST }}" || ssh-keyscan ${{ secrets.GITLAB_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts  # Add this line

      - name: Run Ansible playbook (17.0)
        run: ansible-playbook -i inventory gitlab_upgrade.yml
        continue-on-error: true

      - name: Update playbook for 17.3
        run: |
          sed -i 's/target_version: 17.0/target_version: 17.3/g' gitlab_upgrade.yml
          # No need to modify version_check.sh, it's already in the repo

      - name: Run Ansible playbook (17.3)
        run: ansible-playbook -i inventory gitlab_upgrade.yml
        continue-on-error: true
